server:
  port: 8080

springdoc:
  swagger-ui:
    use-root-path: true

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      data-locations: classpath:data-dev.sql